const ACTION_TYPES = {
  GAME: {
    GET_THEMES: "GET_THEMES",
    GET_TOP_THEMES: "GET_TOP_THEMES",
  },
  LEADERBOARD: {
    GET_LEADERBOARD: "GET_LEADERBOARD",
    ADD_RESULTS: "ADD_RESULTS",
  },
  SESSION: {
    GET_SESSION_SET: "GET_SESION_SET",
    GET_QUESTION_FROM_SESSION: "GET_QUESTION_FROM_SESSION",
  },
  USER: {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    GET_USER_DATA: "GET_USER_DATA",
    UPDATE_USER_DATA: "UPDATE_USER_DATA",
  },
};

export default ACTION_TYPES;
